version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=abcde
      - MYSQL_USER=admin
      - MYSQL_DATABASE=aws_project_01
